apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - image: nginx
    name: cont3
    command: ["/bin/bash", "-c", "while true; do echo c1;sleep 5;done"]
    env:
     - name: myname
       value: chandu
